spring:
  application:
    name: business-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    schemas: business
    default-schema: business
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: business
    show-sql: true