CREATE TABLE business.transportadora
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social  VARCHAR(255) NOT NULL,
    nome_fantasia VARCHAR(255),
    cnpj          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    telefone      VARCHAR(255),
    ativa         BOOLEAN NOT NULL,

    CONSTRAINT uk_transportadora_cnpj UNIQUE (cnpj)
);