CREATE TABLE business.endereco
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logradouro        VARCHAR(255) NOT NULL,
    numero            VARCHAR(20),
    complemento       VARCHAR(255),
    bairro            VARCHAR(100),
    cidade            VARCHAR(100) NOT NULL,
    estado            VARCHAR(2) NOT NULL,
    cep               VARCHAR(20) NOT NULL,
    transportadora_id BIGINT NOT NULL,

    CONSTRAINT fk_endereco_transportadora
        FOREIGN KEY (transportadora_id)
            REFERENCES business.transportadora (id),

    CONSTRAINT uk_endereco_transportadora
        UNIQUE (transportadora_id)
);